version: "3.7"
services:
  # Image
  teleopdocker:
    image: elandini84/yarpwebteleop:sim
    build:
      context: .
      network: host
      dockerfile: Dockerfile.test
    ports:
      - "16001:16001"

  web-teleop-ros:
    image: elandini84/yarpwebteleop:sim
    container_name: web-teleop-ros
    environment:
      - YARP_FORWARD_LOG_ENABLE=1
      - YARP_FORWARD_CODEINFO_ENABLE=1
    command: bash -c "echo ciaoo && echo ciaoo && echo ciaoo && echo ciaoo && source /opt/ros/noetic/setup.bash && roscore"
    network_mode: host
    ipc: host

  web-teleop-yarp:
    image: elandini84/yarpwebteleop:sim
    container_name: web-teleop-server
    environment:
      - YARP_FORWARD_LOG_ENABLE=1
      - YARP_FORWARD_CODEINFO_ENABLE=1
    command: sh -c "yarp server --ros"
    network_mode: host
    ipc: host
    depends_on:
      - web-teleop-ros

  web-teleop-host:
    image: elandini84/yarpwebteleop:sim
    container_name: web-teleop-host
    environment:
      - DISPLAY=host.docker.internal:0
      - YARP_FORWARD_LOG_ENABLE=1
      - YARP_FORWARD_CODEINFO_ENABLE=1
      - QT_X11_NO_MITSHM=1
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${XAUTHORITY}/:/home/user1/.Xauthority:rw"
      - "C:/ExchangeData:/home/user1/ex_data_mount"
      - "C:/Projects/Stuff:/home/user1/ex_stuff"
      - "C:/Projects/GIT/:/home/user1/mntCode"
    command: bash -c "yarp detect --write && yarp run --server /console --log"
    network_mode: host
    ipc: host
    depends_on:
      - web-teleop-yarp

  web-teleop-gazebo:
    image: elandini84/yarpwebteleop:sim
    container_name: web-teleop-gazebo
    environment:
      - DISPLAY=host.docker.internal:0
      - YARP_FORWARD_LOG_ENABLE=1
      - YARP_FORWARD_CODEINFO_ENABLE=1
      - QT_X11_NO_MITSHM=1
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${XAUTHORITY}/:/home/user1/.Xauthority:rw"
      - "C:/ExchangeData:/home/user1/ex_data_mount"
      - "C:/Projects/Stuff:/home/user1/ex_stuff"
      - "C:/Projects/GIT/:/home/user1/mntCode"
    command: bash -c "sleep 5 && yarp detect --write && source /opt/ros/noetic/setup.bash && rosrun gazebo_ros gazebo -s libgazebo_yarp_clock.so --verbose"
    network_mode: host
    ipc: host
    depends_on:
      - web-teleop-yarp

  wep-teleop-server:
    image: elandini84/yarpwebteleop:sim
    container_name: bt-ros-gazebo
    environment:
      - DISPLAY=host.docker.internal:0
      - YARP_FORWARD_LOG_ENABLE=1
      - YARP_FORWARD_CODEINFO_ENABLE=1
      - QT_X11_NO_MITSHM=1
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${XAUTHORITY}/:/home/user1/.Xauthority:rw"
      - "C:/ExchangeData:/home/user1/ex_data_mount"
      - "C:/Projects/Stuff:/home/user1/ex_stuff"
      - "C:/Projects/GIT/:/home/user1/mntCode"
    command: bash -c "sleep 5 && yarp detect --write && cd /home/user1/yarp-web-teleop && python3 server.py"
    network_mode: host
    ipc: host
    depends_on:
      - web-teleop-gazebo